module.exports.jobField = [
  "Land-, Tier- und Forstwirtschaftsberufe",
  "Gartenbauberufe und Floristik",
  "Rohstoffgewinnung und -aufbereitung",
  "Kunststoffherstellung und -verarbeitung",
  "Papier und Druckberufe",
  "Metallerzeugung und -bearbeitung",
  "Textil und Lederberufe",
  "Produktdesign und Kunsthandwerkliche Berufe",
  "Maschinenbau und Betriebstechnik",
  "Fahrzeug-, Luft-, Raumfahrt- und Schiffbautechnik",
  "Bauplanung und -überwachung, Architektur",
  "Vermessung und Kartografie",
  "Medizinische Gesundheitsberufe",
  "Medizintechnische Berufe",
  "Lebensmittelherstellung und -verarbeitung",
  "Tourismus, Hotel- und Gaststättenberufe",
  "Einkaufs-, Vertriebs- und Handelsberufe",
  "Verkaufsberufe",
  "Erziehung, soziale und hauswirtschaftliche Berufe, Theologie",
  "Lehrende und ausbildende Berufe",
  "Wissenschaftrliche Berufe",
  "Darstellende und unterhaltende Berufe",
  "Unternehmensführung und -organisation",
  "Finanzdienstleistungen, Rechnungswesen und Steuerberatung",
  "Recht und Verwaltung",
  "Werbung, Marketing, Medienberufe",
  "Mathematik-, Bielogie-, Chemie- und Physikberufe",
  "Geologie-, Geografie- und Umweltschutzberufe",
  "Informatik und Kommunikationstechnologie",
  "Schutz-, Sicherheits- und Überwachungsberufe",
  "Angehörige der regulären Streitkräfte",
  "Verkehrs- und Logistikberufe",
  "Führen von Fahrzeug- und Transportgeräten",
  "Reinigungsberufe"
]

module.exports.jobType = ['Arbeit', 'Ausbildung/Duales Studium', 'Praktikum']

module.exports.worktime = ['Vollzeit', 'Teilzeit', 'Homeoffice', 'Minijob']